[package]
name = "egui-tetra"
version = "0.3.0"
authors = ["Andrew Minnich <aminnich3@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "egui integration for Tetra"
repository = "https://github.com/tesselode/egui-tetra"
keywords = ["gamedev", "gui"]
categories = ["game-development", "gui"]

[dependencies]
copypasta = "0.10"
egui = "0.27"
open = "5"
tetra = { version = "0.8", default-features = false }

[dev-dependencies]
egui_plot = "0.27"